---
- name: 'Laboratorio de Variables'
  hosts: nodos
  vars_files:
    'vars/default.yml'
  vars:
    gruposdesistema: # root ya existe
      - ctic
      - devops
      - everis

  tasks:

    - name: "Instalar servicios declarados en vars/default.yml"
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ paquetes }}"

    - name: "Arrancar los servicios declarados"
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ servicios }}"
    
    - name: "Crear grupos de sistema desde variable definida en playbook"
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ gruposdesistema }}"

    - name: "Crear usuario administrador"
      user:
        name: "administrador"
        group: "{{ usuarios['administrador']['grupo'] }}"
        generate_ssh_key: "{{ usuarios['administrador']['generar_key'] }}" 
        ssh_key_file: "{{ usuarios['administrador']['ruta_key'] }}" 
        expires: "{{ usuarios['administrador']['expira'] }}"
        state: present     

    - name: "Crear usuario ยก everis_pruebas"
      user:
        name: "everis_pruebas"
        group: "{{ usuarios['everis_pruebas']['grupo'] }}"
        generate_ssh_key: "{{ usuarios['everis_pruebas']['generar_key'] }}" 
        uid: "{{ usuarios['everis_pruebas']['identificador'] }}" 
        expires: "{{ usuarios['everis_pruebas']['expira'] }}"
        state: present     

    - name: "Crear usuario nuestro"
      user:
        name: "nuestro"
        groups: "{{ usuarios['nuestro']['grupo'] }}"
        generate_ssh_key: "{{ usuarios['nuestro']['generar_key'] }}" 
        ssh_key_file: "{{ usuarios['nuestro']['ruta_key'] }}" 
        expires: "{{ usuarios['nuestro']['expira'] }}"
        state: present     

    - name: "Reiniciar servicios"
      systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ servicios }}"

    - name: "Reiniciar los nodos"
      reboot:
...